# Generated by Django 5.2.17 on 2026-08-14 08:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamemove',
            name='player_id',
            field=models.CharField(blank=True, default='', max_length=48),
        ),
        migrations.AddField(
            model_name='gameroom',
            name='game_type',
            field=models.CharField(choices=[('ludo', 'Classic Ludo'), ('snakes', 'Snakes and Ladders')], default='ludo', max_length=12),
        ),
        migrations.AddField(
            model_name='gameroom',
            name='max_players',
            field=models.PositiveSmallIntegerField(default=2, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AddField(
            model_name='gameroom',
            name='state',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='RoomPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.CharField(max_length=48)),
                ('nickname', models.CharField(max_length=32)),
                ('color', models.CharField(default='red', max_length=12)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('is_connected', models.BooleanField(default=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='game.gameroom')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('room', 'player_id'), name='unique_player_in_room')],
            },
        ),
    ]
