# Generated by Django 5.2.17 on 2026-08-14 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_gamemove_player_id_gameroom_game_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameroom',
            name='game_type',
            field=models.CharField(choices=[('snakes', 'Snakes and Ladders')], default='snakes', max_length=12),
        ),
    ]
