/**
 * Snake & Ladders mobile reminder: the lobby exposes only three clear paths—
 * solo practice, random match, or a shareable friend room.
 */
import { Bot, ChevronLeft, Copy, Crown, Dices, RotateCcw, Search, Shuffle, UsersRound, Volume2, VolumeX, Wifi, X } from "lucide-react";
import { CSSProperties, useEffect, useRef, useState } from "react";
import { toast } from "sonner";
import { BrandMark } from "@/components/BrandMark";
import { playGameSound } from "@/lib/gameSounds";

type Mode = "lobby" | "practice" | "friends" | "online-play" | "random";
type Player = "you" | "bot";
type Positions = Record<Player, number>;
type OnlineState = { status: string; players: { id: string; nickname: string; connected: boolean }[]; state: { active_player?: string; positions?: Record<string, number>; last_dice?: number; winner?: string | null } };
const ladders: Record<number, number> = { 2: 23, 8: 34, 20: 77, 32: 68, 41: 79, 74: 92 };
const snakes: Record<number, number> = { 99: 9, 95: 75, 88: 24, 62: 19, 48: 26, 36: 6 };
const pips: Record<number, number[]> = { 1: [4], 2: [0, 8], 3: [0, 4, 8], 4: [0, 2, 6, 8], 5: [0, 2, 4, 6, 8], 6: [0, 2, 3, 5, 6, 8] };
const initialMode = (): Mode => new URLSearchParams(window.location.search).get("mode") === "random" ? "random" : new URLSearchParams(window.location.search).get("mode") === "friends" ? "friends" : "lobby";

function squarePosition(square: number) { const offset = square - 1; const rowFromBottom = Math.floor(offset / 10); const columnOffset = offset % 10; return { row: 10 - rowFromBottom, column: rowFromBottom % 2 === 0 ? columnOffset + 1 : 10 - columnOffset }; }
function pixel(square: number) { const { row, column } = squarePosition(square); return { x: (column - 0.5) * 100, y: (row - 0.5) * 100 }; }
function sleep(ms: number) { return new Promise((resolve) => window.setTimeout(resolve, ms)); }
function Ladder({ from, to }: { from: number; to: number }) { const start = pixel(from); const end = pixel(to); const dx = end.x - start.x; const dy = end.y - start.y; const length = Math.hypot(dx, dy); const normal = { x: (-dy / length) * 12, y: (dx / length) * 12 }; return <g className="ladder-art"><line x1={start.x + normal.x} y1={start.y + normal.y} x2={end.x + normal.x} y2={end.y + normal.y} /><line x1={start.x - normal.x} y1={start.y - normal.y} x2={end.x - normal.x} y2={end.y - normal.y} />{Array.from({ length: 5 }, (_, index) => { const t = (index + 1) / 6; const x = start.x + dx * t; const y = start.y + dy * t; return <line key={index} x1={x + normal.x} y1={y + normal.y} x2={x - normal.x} y2={y - normal.y} />; })}</g>; }
function Snake({ from, to }: { from: number; to: number }) { const start = pixel(from); const end = pixel(to); const midX = (start.x + end.x) / 2; const midY = (start.y + end.y) / 2; return <g className="snake-art"><path d={`M ${start.x} ${start.y} Q ${midX + 90} ${midY - 70} ${end.x} ${end.y}`} /><circle cx={start.x} cy={start.y} r="20" /></g>; }
function SnakeBoard({ positions, moving, jump, opponentLabel }: { positions: Positions; moving: Player | null; jump: "ladder" | "snake" | null; opponentLabel: string }) { const you = squarePosition(Math.max(positions.you, 1)); const bot = squarePosition(Math.max(positions.bot, 1)); return <div className={`snake-board-stage ${jump ? `is-${jump}` : ""}`}><div className="snake-board" aria-label="صفحهٔ مار و پله">{Array.from({ length: 100 }, (_, index) => { const square = index + 1; const position = squarePosition(square); return <div key={square} className={`snake-cell ${ladders[square] ? "is-ladder" : ""} ${snakes[square] ? "is-snake" : ""}`} style={{ gridRow: position.row, gridColumn: position.column }}><span>{square}</span></div>; })}<svg className="board-art" viewBox="0 0 1000 1000" preserveAspectRatio="none" aria-hidden="true">{Object.entries(ladders).map(([from, to]) => <Ladder key={from} from={Number(from)} to={to} />)}{Object.entries(snakes).map(([from, to]) => <Snake key={from} from={Number(from)} to={to} />)}</svg><span className={`snake-piece you-piece ${moving === "you" ? "is-moving" : ""}`} style={{ gridRow: you.row, gridColumn: you.column } as CSSProperties}>آ</span><span className={`snake-piece bot-piece ${moving === "bot" ? "is-moving" : ""}`} style={{ gridRow: bot.row, gridColumn: bot.column } as CSSProperties}>ر</span><div className="finish-crown"><Crown size={15} /><small>100</small></div></div><div className="board-compass"><i /> خانهٔ تو <span>—</span> خانهٔ {opponentLabel} <i className="bot" /></div></div>; }

export function ClassicGames() {
  const [mode, setMode] = useState<Mode>(initialMode);
  const [positions, setPositions] = useState<Positions>({ you: 0, bot: 0 });
  const [turn, setTurn] = useState<Player>("you");
  const [dice, setDice] = useState(1); const [rolling, setRolling] = useState(false); const [moving, setMoving] = useState<Player | null>(null); const [jump, setJump] = useState<"ladder" | "snake" | null>(null); const [winner, setWinner] = useState<Player | null>(null); const [soundOn, setSoundOn] = useState(true);
  const [roomCode, setRoomCode] = useState(""); const [onlineRoom, setOnlineRoom] = useState(""); const [onlineState, setOnlineState] = useState<OnlineState | null>(null); const [onlineStatus, setOnlineStatus] = useState<"idle" | "connecting" | "waiting" | "ready" | "error">("idle"); const [queueMessage, setQueueMessage] = useState("در حال پیدا کردن حریف…");
  const [playerId] = useState(() => `snake-${Math.random().toString(36).slice(2, 10)}`); const socketRef = useRef<WebSocket | null>(null); const matchSocketRef = useRef<WebSocket | null>(null); const isOnline = mode === "online-play";
  useEffect(() => () => { socketRef.current?.close(); matchSocketRef.current?.close(); }, []);
  const wsBase = () => (import.meta.env.VITE_DJANGO_WS_URL ?? "").replace(/\/$/, "");
  const reset = () => { setPositions({ you: 0, bot: 0 }); setTurn("you"); setDice(1); setWinner(null); setJump(null); setMoving(null); };
  const specialMove = async (player: Player, landed: number) => { const type = ladders[landed] ? "ladder" : snakes[landed] ? "snake" : null; if (!type) return landed; setJump(type); playGameSound(type, soundOn); toast(type === "ladder" ? "پله پیدا کردی!" : "مار به دام انداخت!", { description: type === "ladder" ? `از ${landed} به ${ladders[landed]} صعود کردی.` : `از ${landed} به ${snakes[landed]} برگشتی.` }); await sleep(520); const destination = type === "ladder" ? ladders[landed] : snakes[landed]; setPositions((current) => ({ ...current, [player]: destination })); await sleep(280); setJump(null); return destination; };
  const movePiece = async (player: Player, value: number) => { const current = positions[player]; if (current + value > 100) { playGameSound("blocked", soundOn); toast("برای رسیدن به ۱۰۰ باید تاس دقیق بیاوری"); return false; } setMoving(player); for (let next = current + 1; next <= current + value; next += 1) { setPositions((state) => ({ ...state, [player]: next })); playGameSound("step", soundOn); await sleep(130); } const finalSquare = await specialMove(player, current + value); setMoving(null); if (finalSquare === 100) { setWinner(player); playGameSound("win", soundOn); toast(player === "you" ? "بردی!" : "حریف برنده شد", { description: "به خانهٔ ۱۰۰ رسید." }); return true; } return false; };
  const botTurn = async () => { setTurn("bot"); await sleep(650); const value = Math.floor(Math.random() * 6) + 1; setDice(value); playGameSound("roll", soundOn); await sleep(350); const won = await movePiece("bot", value); if (!won) setTurn("you"); };
  const practiceRoll = async () => { if (rolling || turn !== "you" || winner) return; setRolling(true); for (let frame = 0; frame < 8; frame += 1) { setDice(Math.floor(Math.random() * 6) + 1); playGameSound("roll", soundOn); await sleep(72); } const value = Math.floor(Math.random() * 6) + 1; setDice(value); setRolling(false); const won = await movePiece("you", value); if (!won) void botTurn(); };
  const applyRoomState = (state: OnlineState) => { setOnlineState(state); setOnlineStatus(state.status === "active" ? "ready" : "waiting"); setTurn(state.state.active_player === playerId ? "you" : "bot"); const values = state.state.positions ?? {}; const opponent = Object.entries(values).find(([id]) => id !== playerId)?.[1] ?? 0; setPositions({ you: values[playerId] ?? 0, bot: opponent }); if (state.state.winner) setWinner(state.state.winner === playerId ? "you" : "bot"); };
  const connectRoom = (code: string, autoStart = false) => { const base = wsBase(); if (!base) { setOnlineStatus("error"); return toast("سرور آنلاین تنظیم نشده", { description: "برای بازی واقعی، VITE_DJANGO_WS_URL را تنظیم کن." }); } socketRef.current?.close(); setOnlineRoom(code); setOnlineStatus("connecting"); const socket = new WebSocket(`${base}/ws/rooms/${code}/`); socketRef.current = socket; socket.onopen = () => socket.send(JSON.stringify({ action: "join", player_id: playerId, nickname: "آرین", game_type: "snakes" })); socket.onerror = () => { setOnlineStatus("error"); toast("اتصال آنلاین برقرار نشد"); }; socket.onmessage = (event) => { const message = JSON.parse(event.data); if (message.type === "room_state") { applyRoomState(message); if (autoStart && message.status === "active") setMode("online-play"); } if (message.type === "roll") { setRolling(false); if (message.ok) { setDice(message.dice_value); socket.send(JSON.stringify({ action: "move", token_id: playerId })); } else toast(message.message); } if (message.type === "move" && message.ok) { setMoving("you"); window.setTimeout(() => setMoving(null), 280); if (message.event === "ladder") toast("پله پیدا کردی!"); if (message.event === "snake") toast("مار به دام انداخت!"); if (message.event === "blocked") toast("برای ۱۰۰ باید تاس دقیق بیاوری"); if (message.winner) toast("بازیکن برنده شد!"); } if (message.type === "error") toast(message.message); }; };
  const startRandom = () => { const base = wsBase(); if (!base) return toast("سرور آنلاین تنظیم نشده", { description: "برای مسابقهٔ تصادفی، VITE_DJANGO_WS_URL را تنظیم کن." }); setMode("random"); setQueueMessage("در حال پیدا کردن حریف…"); const socket = new WebSocket(`${base}/ws/matchmaking/`); matchSocketRef.current = socket; socket.onopen = () => socket.send(JSON.stringify({ action: "queue", player_id: playerId, nickname: "آرین" })); socket.onerror = () => { setQueueMessage("اتصال صف ناموفق بود"); }; socket.onmessage = (event) => { const message = JSON.parse(event.data); if (message.type === "queued") setQueueMessage(message.message); if (message.type === "match_found") { socket.close(); reset(); connectRoom(message.room_code, true); setQueueMessage(`حریف ${message.opponent} پیدا شد`); } if (message.type === "error") { setQueueMessage(message.message); toast(message.message); } }; };
  const cancelRandom = () => { matchSocketRef.current?.send(JSON.stringify({ action: "cancel" })); matchSocketRef.current?.close(); setMode("lobby"); };
  const enterFriendRoom = () => { const code = roomCode.trim().toUpperCase() || `SNAKE-${Math.random().toString(36).slice(2, 6).toUpperCase()}`; connectRoom(code); };
  const copyRoom = async () => { if (!onlineRoom) return; try { await navigator.clipboard.writeText(onlineRoom); toast("کد اتاق کپی شد", { description: "برای دوستت بفرست." }); } catch { toast(`کد اتاق: ${onlineRoom}`); } };
  const onlineRoll = () => { if (socketRef.current?.readyState !== WebSocket.OPEN) return toast("اتصال هنوز آماده نیست"); setRolling(true); socketRef.current.send(JSON.stringify({ action: "roll" })); };
  const opponentLabel = isOnline ? onlineState?.players.find((player) => player.id !== playerId)?.nickname ?? "حریف" : "ربات";

  if (mode === "lobby") return <section className="snake-lobby"><div className="snake-hero"><div className="snake-brand"><BrandMark /><span><i /> SNAKES & LADDERS</span></div><div><small>مسیر آماده است</small><h2>تا خانهٔ ۱۰۰ بالا برو.</h2><p>تمرین کن، حریف تصادفی پیدا کن یا دوستت را به یک اتاق خصوصی دعوت کن.</p></div><div className="snake-match-ticker"><span><b>100</b> PATH</span><i /><span><b>02</b> PLAYERS</span><i /><span><b>LIVE</b> MATCH</span></div><div className="snake-hero-rail"><span>READY // 01</span><i /><b>یک مسیر، یک برنده</b></div></div><article className="snake-primary-card"><span className="main-event-label"><i /> QUICK MATCH</span><div className="primary-art"><span>VS</span><i>↗</i></div><div><small>حریف هم‌سطح</small><h3>مسابقهٔ تصادفی</h3><p>در صف قرار بگیر؛ با اولین بازیکن آماده وارد میز زنده می‌شوی.</p><button className="primary-button" onClick={startRandom}><Shuffle size={17} /> پیدا کردن حریف</button></div></article><div className="snake-action-rail"><button onClick={() => { reset(); setMode("practice"); }}><Bot size={18} /><span><b>تمرین با ربات</b><small>بدون انتظار</small></span><ChevronLeft size={16} /></button><button onClick={() => setMode("friends")}><UsersRound size={18} /><span><b>اتاق دوستان</b><small>کد اختصاصی</small></span><ChevronLeft size={16} /></button></div><div className="snake-rules-mini"><span>قانون دقیق</span><p>حرکت فقط تا ۱۰۰ مجاز است؛ پله صعود می‌دهد و سرِ مار بازیکن را پایین می‌آورد.</p></div></section>;
  if (mode === "random") return <section className="matchmaking-page"><button className="back-link" onClick={cancelRandom}>بازگشت <ChevronLeft size={15} /></button><div className="matchmaking-orbit"><i /><i /><i /><Search size={27} /></div><small>QUICK MATCH // LIVE</small><h2>در صف مسابقه‌ای.</h2><p>{queueMessage}</p><div className="queue-status"><span><i /> اتصال امن</span><span><i /> قوانین رسمی</span></div><button className="surface-button queue-cancel" onClick={cancelRandom}><X size={15} /> لغو جست‌وجو</button></section>;
  if (mode === "friends") return <section className="snake-online-page"><button className="back-link" onClick={() => setMode("lobby")}>بازی‌ها <ChevronLeft size={15} /></button><div className="snake-page-title"><small>اتاق خصوصی</small><h2>دوستت را وارد بازی کن.</h2><p>یک کد کوتاه بساز یا کد دریافت‌شده را وارد کن.</p></div><label className="snake-room-input"><span>کد اتاق</span><input value={roomCode} onChange={(event) => setRoomCode(event.target.value)} placeholder="مثلاً SNAKE-7P2A" /></label><button className="primary-button snake-room-submit" onClick={enterFriendRoom}><UsersRound size={17} /> ساخت یا ورود به اتاق</button>{onlineRoom && <div className={`snake-room-state ${onlineStatus === "ready" ? "is-ready" : ""}`}><Wifi size={18} /><div><b>{onlineStatus === "ready" ? "حریف متصل شد" : "اتاق آماده است"}</b><small>{onlineStatus === "connecting" ? "در حال اتصال…" : onlineStatus === "ready" ? "میز آمادهٔ شروع است." : `کد ${onlineRoom} را برای دوستت بفرست.`}</small></div><button className="copy-room" onClick={copyRoom} aria-label="کپی کد اتاق"><Copy size={15} /></button></div>}{onlineStatus === "ready" && <button className="primary-button snake-room-submit" onClick={() => { reset(); setMode("online-play"); }}>شروع بازی دوستانه</button>}</section>;
  return <section className="snake-match"><div className="snake-match-top"><button className="back-link" onClick={() => setMode(isOnline ? "friends" : "lobby")}>خروج <ChevronLeft size={15} /></button><button className={`sound-toggle ${soundOn ? "is-on" : ""}`} onClick={() => setSoundOn((enabled) => !enabled)}>{soundOn ? <Volume2 size={16} /> : <VolumeX size={16} />} {soundOn ? "صدا روشن" : "بی‌صدا"}</button></div><header className="snake-status"><span className={turn === "you" ? "is-active" : ""}>{turn === "you" ? "نوبت توست" : isOnline ? "نوبت حریف" : "ربات در حال حرکت"}</span><h2>مار و پله</h2><small>{winner ? (winner === "you" ? "تاج برای توست" : `${opponentLabel} به تاج رسید`) : "برای رسیدن به ۱۰۰، تاس دقیق بیاور."}</small></header><SnakeBoard positions={positions} moving={moving} jump={jump} opponentLabel={opponentLabel} /><div className="snake-score"><span><b>{positions.you}</b> خانهٔ تو</span><i /><span><b>{positions.bot}</b> {opponentLabel}</span></div><div className="snake-dice-panel"><div className={`snake-dice ${rolling ? "is-rolling" : ""}`}>{Array.from({ length: 9 }, (_, index) => <i key={index} className={pips[dice].includes(index) ? "" : "blank"} />)}</div><div><button className="primary-button snake-roll" onClick={isOnline ? onlineRoll : practiceRoll} disabled={rolling || turn !== "you" || Boolean(winner)}><Dices size={18} /> {rolling ? "تاس در حال چرخش" : turn !== "you" ? "نوبت حریف" : "تاس بریز"}</button><button className="surface-button snake-reset" onClick={reset}><RotateCcw size={15} /> شروع دوباره</button></div></div></section>;
}
